name: Deploy

on:
  push:
    branches:
      - main
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm i
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "POSTGRES_URL_NON_POOLING=\"${{ secrets.PRODUCTION_POSTGRES_URL_NON_POOLING }}\"" >> .env
          echo "PRISMA_ACCELERATE_URL=\"${{ secrets.PRODUCTION_PRISMA_ACCELERATE_URL }}\"" >> .env
          echo "CLERK_ENDPOINT=\"${{ secrets.PRODUCTION_CLERK_ENDPOINT }}\"" >> .env
          echo "CLERK_SECRET_KEY=\"${{ secrets.PRODUCTION_CLERK_SECRET_KEY }}\"" >> .env
          npx partykit deploy --with-vars
        env:
          PARTYKIT_TOKEN: ${{ secrets.PARTYKIT_TOKEN }}
          PARTYKIT_LOGIN: ${{ secrets.PARTYKIT_LOGIN }}
      - name: Deploy to staging
        if: github.ref != 'refs/heads/main'
        run: |
          echo "POSTGRES_URL_NON_POOLING=\"${{ secrets.STAGING_POSTGRES_URL_NON_POOLING }}\"" >> .env
          echo "PRISMA_ACCELERATE_URL=\"${{ secrets.STAGING_PRISMA_ACCELERATE_URL }}\"" >> .env
          echo "CLERK_SECRET_KEY=\"${{ secrets.STAGING_CLERK_SECRET_KEY }}\"" >> .env
          npx partykit deploy --preview staging --with-vars
        env:
          PARTYKIT_TOKEN: ${{ secrets.PARTYKIT_TOKEN }}
          PARTYKIT_LOGIN: ${{ secrets.PARTYKIT_LOGIN }}
