name: Deploy

on:
  push:
    branches:
      - main
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Configure PartyKit for production
        if: github.ref == 'refs/heads/main'
        run: |
          content=$(cat partykit.json | 
            sed 's#\$POSTGRES_URL_NON_POOLING#${{ secrets.PRODUCTION_POSTGRES_URL_NON_POOLING }}#g' |
            sed 's#\$PRISMA_ACCELERATE_URL#${{ secrets.PRODUCTION_PRISMA_ACCELERATE_URL }}#g' |
            sed 's#\$CLERK_ENDPOINT#${{ secrets.PRODUCTION_CLERK_ENDPOINT }}#g')
          echo "$content" > partykit.json

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: npx partykit deploy
        env:
          PARTYKIT_TOKEN: ${{ secrets.PARTYKIT_TOKEN }}
          PARTYKIT_LOGIN: ${{ secrets.PARTYKIT_LOGIN }}

      - name: Configure PartyKit for staging
        if: github.ref != 'refs/heads/main'
        run: |
          content=$(cat partykit.json | 
            sed 's#\$POSTGRES_URL_NON_POOLING#${{ secrets.STAGING_POSTGRES_URL_NON_POOLING }}#g' |
            sed 's#\$PRISMA_ACCELERATE_URL#${{ secrets.STAGING_PRISMA_ACCELERATE_URL }}#g' |
            sed 's#\$CLERK_ENDPOINT#${{ secrets.STAGING_CLERK_ENDPOINT }}#g')
          echo "$content" > partykit.json

      - name: Deploy to staging
        if: github.ref != 'refs/heads/main'
        run: npx partykit deploy --preview staging
        env:
          PARTYKIT_TOKEN: ${{ secrets.PARTYKIT_TOKEN }}
          PARTYKIT_LOGIN: ${{ secrets.PARTYKIT_LOGIN }}
